version: '3'
services:
  backend:
    build: .
    container_name: backend
    tty: true
    volumes:
      - .:/workspace
    networks:
      - backend
      - frontend
    ports:
      - 3001:3000
    depends_on:
      - db
  frontend:
    build: .
    container_name: frontend
    tty: true
    volumes:
      - .:/workspace
    networks:
      - frontend 
    ports:
      - 8080:3000
    depends_on:
      - backend
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - backend
    ports:
      - '5432:5432'
networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge